services:
  - type: web
    name: pubg-scraper
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget unzip curl
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb

      CHROME_VERSION=$(google-chrome --version | grep -oP "\d+" | head -1)
      CHROMEDRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)

      wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/bin/chromedriver
      chmod +x /usr/bin/chromedriver

      python3 -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
